services:
  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo-td
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'secret'
      MONGO_INITDB_DATABASE: todo
    ports:
      - "27017:27017"
    volumes:
      - ./init-script.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: mongo-express-td
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'secret'
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_BASICAUTH_USERNAME: 'admin'
      ME_CONFIG_BASICAUTH_PASSWORD: 'admin'
    links:
      - mongo
    ports:
      - "8081:8081"